[package]
name = "vosk-sys"
version = "0.1.0"
edition = "2021"
authors = ["Bear_03"]
description = "Raw FFI bindings around the Vosk API Speech Recognition library"
keywords = ["speech", "speech-to-text", "stt"]
categories = ["multimedia::audio"]

[dependencies]
