name: CI

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly


    steps:
    - uses: actions/checkout@v3

    - name: Install apt packages
      run: sudo apt install libasound2-dev

    - name: Download libraries
      run: wget https://github.com/alphacep/vosk-api/releases/download/v0.3.42/vosk-linux-x86_64-0.3.42.zip -O libs.zip

    - name: Extract libraries
      run: sudo unzip -j libs.zip -d /lib

    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test
